"""
contribtriage/resolver/installer.py

Stage 5 — User Consent Gate + Command Executor.

This module is called by apply_fix_node in graph/nodes.py.
It is intentionally thin: it handles ONLY the consent prompt and subprocess
execution.  It does NOT decide WHAT to install — that is Groq's job.
It does NOT update LangGraph state — that is apply_fix_node's job.

The caller (apply_fix_node) is responsible for:
  1. Getting fix_command from state (set by analyze_failure_node)
  2. Calling run_fix_command()
  3. Appending the returned log to terminal_log_history
  4. Incrementing retry_count

Return contract
───────────────
  (success: bool, log: str, declined: bool)
  - success=True,  declined=False  → command ran and exited 0
  - success=False, declined=False  → command ran and exited non-0
  - success=False, declined=True   → user said N; no command was run
"""

from __future__ import annotations

import subprocess
from typing import Tuple

from rich.console import Console
from rich.panel import Panel

console = Console()

_TIMEOUT = 120  # seconds


# ===========================================================================
# Public API
# ===========================================================================

def run_fix_command(
    fix_command: str,
    yes_flag: bool,
    repo_root: str,
) -> Tuple[bool, str, bool]:
    """
    Present the LLM-generated fix command to the user and optionally execute it.

    Args:
        fix_command: The exact shell command string from Groq.
        yes_flag:    If True, execute without prompting (--yes CLI flag).
        repo_root:   Working directory for the subprocess.

    Returns:
        (success, log, declined)
    """
    if not fix_command or not fix_command.strip():
        return False, "[ContribTriage] No fix command provided.", False

    _show_command_panel(fix_command)

    # ── Consent gate ──────────────────────────────────────────────────────
    if not _get_consent(fix_command, yes_flag):
        return False, "User declined the proposed fix.", True

    # ── Execute ───────────────────────────────────────────────────────────
    return _execute(fix_command, repo_root)


# ===========================================================================
# Consent prompt
# ===========================================================================

def _show_command_panel(fix_command: str) -> None:
    """Render a Rich panel showing the proposed fix."""
    console.print(Panel(
        f"[bold yellow]{fix_command}[/bold yellow]",
        title="🔧  Proposed Fix Command",
        subtitle="[dim]Generated by Groq Llama 3[/dim]",
        border_style="yellow",
    ))


def _get_consent(fix_command: str, yes_flag: bool) -> bool:
    """
    Ask the user whether to run the fix.
    Returns True if accepted, False if declined.
    """
    if yes_flag:
        console.print("[dim]  --yes flag set — auto-accepting.[/dim]")
        return True

    try:
        answer = input("  Run this command? [Y/n]  ").strip().lower()
        return answer in ("", "y", "yes")
    except (EOFError, KeyboardInterrupt):
        # Non-interactive context (CI) — treat as declined
        console.print("[dim]  Non-interactive context — treating as declined.[/dim]")
        return False


# ===========================================================================
# Subprocess executor
# ===========================================================================

def _execute(fix_command: str, repo_root: str) -> Tuple[bool, str, bool]:
    """
    Run fix_command as a native shell subprocess.

    Uses shell=True because the LLM generates full shell strings including
    pipes, flags, and quoted arguments (e.g. `docker run -d -p 5432:5432 postgres:15`).

    Returns (success, log, declined=False).
    Never raises — all errors captured in log.
    """
    console.print(f"[cyan]  → Executing: {fix_command}[/cyan]")
    try:
        proc = subprocess.run(
            fix_command,
            shell=True,
            cwd=repo_root,
            capture_output=True,
            text=True,
            timeout=_TIMEOUT,
        )
        log     = _combine(proc.stdout, proc.stderr)
        success = proc.returncode == 0

        icon = "✓" if success else "✗"
        color = "green" if success else "red"
        console.print(f"  [{color}]  {icon} Exit code {proc.returncode}[/{color}]")
        return success, log, False

    except subprocess.TimeoutExpired:
        msg = f"[ContribTriage] Timed out after {_TIMEOUT}s."
        console.print(f"[red]  ✗ {msg}[/red]")
        return False, msg, False

    except (OSError, Exception) as exc:  # noqa: BLE001
        msg = f"[ContribTriage] Could not execute command: {exc}"
        console.print(f"[red]  ✗ {msg}[/red]")
        return False, msg, False


def _combine(stdout: str, stderr: str) -> str:
    parts = [p.strip() for p in (stdout, stderr) if p and p.strip()]
    return "\n".join(parts)
