"""
contribtriage/agents/groq_agent.py

Groq Llama 3.3-70B Versatile — Debugging & Healing Brain.

Role in the pipeline
────────────────────
  Called exclusively inside the rapid healing loop (Stage 5) because of
  Groq's sub-second LPU latency.  This agent is the ONLY component that
  reads the raw failure context and decides what to do next.

What it receives
────────────────
  The ENTIRE accumulated terminal_log_history, not just the latest run.
  This is the critical difference from a naive "blind loop":
  - First call:  sees the original failing test output
  - Second call: sees test output + install attempt + selective rerun output
  Groq can therefore reason: "I tried pip install X (exit 0), but the test
  still fails — this is now a code bug, not a missing package."

What it returns (strict JSON)
─────────────────────────────
  {
    "failure_category":  "code_bug" | "system_dep" | "app_dep",
    "reasoning":         "<one sentence: WHY did this test fail?>",
    "fix_command":       "<exact copy-pasteable terminal command>" | null,
    "fix_description":   "<one sentence: what the command does>",
    "affected_packages": ["pkg1", "pkg2"]
  }

Design rules
────────────
  - Never raises — Groq API errors default to safe fallback (code_bug).
  - Uses response_format={"type":"json_object"} for guaranteed JSON.
  - Temperature 0.1 — low randomness for deterministic classification.
  - Model: llama-3.3-70b-versatile (best reasoning on Groq's LPU fleet).
"""

from __future__ import annotations

import json
import os
from typing import Any, Dict, List, Optional

from rich.console import Console

console = Console()

_MODEL = "llama-3.3-70b-versatile"

_SAFE_FALLBACK: Dict[str, Any] = {
    "failure_category": "code_bug",
    "reasoning": "Could not parse LLM response — treating as code bug for safety.",
    "fix_command": None,
    "fix_description": "",
    "affected_packages": [],
}

_SYSTEM_PROMPT = """\
You are a seasoned Systems & Reliability Engineer helping a developer set up
a new open-source repository for the first time.

You will receive the COMPLETE accumulated execution history of this session.
This includes every test run, every install attempt, and their outputs —
in chronological order.  Read the FULL history before deciding; earlier
install attempts that FAILED are important context.

The test files were generated by ContribTriage and contain TWO sections:
  1. Import block at the top — verifies all deps are installed.  A failure
     here means a MISSING PACKAGE (app_dep), NOT a code bug.
  2. Test stubs below — failures here are code logic issues (code_bug).

Your task
─────────
A) Classify the ROOT CAUSE of the current test failure as exactly ONE of:
   • "code_bug"   — assertion/logic/type error in test or source code.
                     NOT environment-related. Do NOT suggest any command.
                     Route these to report as contribution opportunities.
   • "system_dep" — a system-level service is unavailable (postgres, redis,
                     elasticsearch, kafka, rabbitmq, MongoDB, etc.).
   • "app_dep"    — a language-level package is missing
                     (Python pip, Node npm/yarn, Rust cargo, Go go get).

B) For "system_dep" and "app_dep" ONLY, generate the EXACT terminal command:
   • Prefer `docker run ...` for system services when Docker is available.
   • Prefer `uv pip install` over `pip install` for Python deps.
   • Prefer `pnpm add` > `yarn add` > `npm install` for Node deps.
   • Use OS-native commands only if Docker is NOT available (apt/brew/choco).
   • If a previous install attempt already failed, try a DIFFERENT approach.

C) Respond ONLY with valid JSON (no prose outside JSON):
{
  "failure_category":  "code_bug" | "system_dep" | "app_dep",
  "reasoning":         "<one sentence: WHY did this test fail?>",
  "fix_command":       "<exact terminal command>" | null,
  "fix_description":   "<one sentence: what the command does>",
  "affected_packages": ["<pkg1>", "<pkg2>"]
}

IMPORTANT: Never classify an ImportError/ModuleNotFoundError as code_bug.
Never classify an AssertionError or TypeError as system_dep or app_dep.

━━━ Language-specific failure classification examples ━━━

Python — app_dep patterns (→ "app_dep"):
  ModuleNotFoundError: No module named 'requests'
  ImportError: cannot import name 'ConfigParser' from 'configparser'
  ERROR: Could not find a version that satisfies the requirement X

JavaScript/Node — app_dep patterns (→ "app_dep"):
  Cannot find module 'axios'
  Module not found: Error: Can't resolve 'lodash'
  Error: Cannot find module './utils/auth'  ← relative path (still app_dep)

Rust — app_dep patterns (→ "app_dep"):
  error[E0432]: unresolved import `serde`
  error[E0433]: failed to resolve: use of undeclared crate or module `tokio`
  error: package `X` not found in any source

Go — app_dep patterns (→ "app_dep"):
  cannot find package "github.com/gin-gonic/gin"
  build failed: go: module X: reading go.mod

System service patterns (→ "system_dep"):
  ECONNREFUSED 127.0.0.1:5432           ← postgres not running
  redis.exceptions.ConnectionError      ← redis not running
  dial tcp [...]:27017: connect          ← MongoDB not running

Logic errors (→ "code_bug"):
  AssertionError: expected X but got Y
  TypeError: cannot read property 'foo' of undefined
  panic: runtime error: index out of range
  FAIL tests/module_test.go:42
  test tests::my_fn ... FAILED"""


# ===========================================================================
# Public API
# ===========================================================================

def analyze_failure(
    raw_output: str,
    env_report,
    project_meta,
    groq_client,
    failed_test_ids: Optional[List[str]] = None,
) -> Dict[str, Any]:
    """
    Send the full accumulated session context to Groq Llama 3 for analysis.

    Args:
        raw_output:      The MERGED terminal_log_history string.
                         This is NOT just the latest test run — it is the
                         concatenation of ALL logs since the session started.
        env_report:      Stage 3 EnvReport (OS, Docker, package managers).
        project_meta:    Stage 2 ProjectMeta (ecosystem, declared deps).
        groq_client:     Initialised groq.Groq() client (injected via state).
        failed_test_ids: Current list of failing test IDs.

    Returns:
        Dict with keys: failure_category, reasoning, fix_command,
                        fix_description, affected_packages.
    """
    user_message = _build_user_message(
        raw_output, env_report, project_meta, failed_test_ids or []
    )

    console.print("[cyan]  → Groq Llama 3 reading full session history…[/cyan]")

    try:
        response = groq_client.chat.completions.create(
            model=_MODEL,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user",   "content": user_message},
            ],
            response_format={"type": "json_object"},
            temperature=0.1,
            max_tokens=512,
        )
        raw_json = response.choices[0].message.content
        result   = _parse_response(raw_json)

    except Exception as exc:  # noqa: BLE001
        console.print(
            f"[yellow]  ⚠ Groq call failed ({exc}) — defaulting to code_bug[/yellow]"
        )
        return dict(_SAFE_FALLBACK)

    category = result.get("failure_category", "code_bug")
    icon = {"code_bug": "🐛", "system_dep": "🔧", "app_dep": "📦"}.get(category, "❓")
    console.print(f"  {icon} [bold]{category}[/bold]: {result.get('reasoning', '')}")
    if result.get("fix_command"):
        console.print(f"  [dim]Proposed fix:[/dim] [yellow]{result['fix_command']}[/yellow]")

    return result


# ===========================================================================
# Prompt builder
# ===========================================================================

def _build_user_message(
    raw_output: str,
    env_report,
    project_meta,
    failed_test_ids: List[str],
) -> str:
    """Build the structured user turn with env + dep + history context."""

    env_section = (
        f"OS          : {getattr(env_report, 'os_name', 'unknown')} "
        f"{getattr(env_report, 'os_version', '')}\n"
        f"Python      : {getattr(env_report, 'python_version', 'unknown')}\n"
        f"Docker      : {'AVAILABLE ✓' if getattr(env_report, 'docker_running', False) else 'NOT available ✗'}\n"
        f"uv          : {'available' if getattr(env_report, 'uv_available', False) else 'not found'}\n"
        f"pip         : {'available' if getattr(env_report, 'pip_available', False) else 'not found'}\n"
        f"npm         : {'available' if getattr(env_report, 'npm_available', False) else 'not found'}\n"
        f"pnpm        : {'available' if getattr(env_report, 'pnpm_available', False) else 'not found'}\n"
        f"Node        : {getattr(env_report, 'node_version', 'not installed')}\n"
        f"Rust/cargo  : {getattr(env_report, 'rust_version', 'not installed')}\n"
        f"Go          : {getattr(env_report, 'go_version', 'not installed')}"
    )

    declared = getattr(project_meta, "declared_deps", []) if project_meta else []
    ecosystem = getattr(project_meta, "ecosystem", "python") if project_meta else "python"
    deps_section = (
        f"Ecosystem   : {ecosystem}\n"
        f"Declared deps ({len(declared)}): "
        f"{', '.join(str(d) for d in declared[:20])}"
    )

    tests_section = (
        "Currently failing test IDs:\n"
        + "\n".join(f"  - {t}" for t in failed_test_ids[:15])
        if failed_test_ids
        else "No specific test IDs available."
    )

    # Use last 6 000 chars to stay within context limits while preserving
    # enough history for Groq to see previous failed install attempts
    history_snippet = raw_output[-6000:] if len(raw_output) > 6000 else raw_output

    return (
        "=== HOST ENVIRONMENT ===\n"
        f"{env_section}\n\n"
        "=== PROJECT DEPENDENCIES ===\n"
        f"{deps_section}\n\n"
        "=== FAILING TESTS ===\n"
        f"{tests_section}\n\n"
        "=== FULL ACCUMULATED SESSION HISTORY (chronological) ===\n"
        f"{history_snippet}"
    )


# ===========================================================================
# Response parser
# ===========================================================================

def _parse_response(raw_json: str) -> Dict[str, Any]:
    """Parse and validate the LLM JSON. Falls back to code_bug on errors."""
    try:
        data = json.loads(raw_json)
    except json.JSONDecodeError:
        console.print("[yellow]  ⚠ Groq response was not valid JSON[/yellow]")
        return dict(_SAFE_FALLBACK)

    valid = {"code_bug", "system_dep", "app_dep"}
    if data.get("failure_category") not in valid:
        console.print(
            f"[yellow]  ⚠ Unknown category '{data.get('failure_category')}' — "
            "defaulting to code_bug[/yellow]"
        )
        data["failure_category"] = "code_bug"
        data["fix_command"] = None

    for key, default in [
        ("reasoning",        "No reasoning provided."),
        ("fix_command",      None),
        ("fix_description",  ""),
        ("affected_packages", []),
    ]:
        data.setdefault(key, default)

    return data
