"""
contribtriage/runners/test_generator.py

Stage 4 — Test Stub Generator.

Two independent generators are provided:

1. generate_test_stubs  — function-coverage stubs
   For every public function flagged as uncovered by Stage 1’s
   KnowledgeGraph.uncovered_funcs, a minimal pytest stub is written
   so contributors immediately see WHAT needs testing and WHERE.

   Output per stub:
       def test_<function_name>():
           \"\"\"Stub for <module>.<function_name> — generated by ContribTriage.\"\"\"
           raise NotImplementedError("...")

2. generate_dep_stubs  — dependency importability tests
   For every declared dependency (from Stage 2 ProjectMeta), a live test
   is written that will PASS when the dep is installed and FAIL with a
   clear ImportError when it is not.  This directly feeds Stage 5’s
   healing loop:

       Stage 4 runs dep tests → ImportError → dep_errors populated
       Stage 5 reads dep_errors → installs missing packages
       Stage 4 reruns → all green

   Python deps: `import <dep>` wrapped in pytest.fail on ImportError
   Node deps:   subprocess `node -e "require('<dep>')"` with pytest.fail

Grouping strategy
─────────────────
  Function stubs  → tests/stubs/test_<module_stem>_stubs.py
  Python dep stubs→ tests/stubs/test_deps_python_stubs.py
  Node dep stubs  → tests/stubs/test_deps_node_stubs.py

Design decisions
────────────────
  - Only PUBLIC functions (not starting with '_') are stubbed.
  - Already-stubbed files are NOT overwritten (idempotent).
  - Returns a list of generated file paths (empty list if nothing to stub).
  - Never raises — OS errors are logged and skipped per file.
"""

from __future__ import annotations

import textwrap
from collections import defaultdict
from pathlib import Path
from typing import Dict, List

from rich.console import Console

console = Console()

# Subdirectory inside the repo's tests/ folder
_STUB_SUBDIR = "stubs"


# ===========================================================================
# Public API
# ===========================================================================

def generate_test_stubs(
    uncovered_funcs: List[str],
    repo_root: str,
    tests_dir: str = "tests",
) -> List[str]:
    """
    Generate pytest stub files for all uncovered public functions.

    Args:
        uncovered_funcs: List of 'module.function' strings from
                         KnowledgeGraph.uncovered_funcs.
        repo_root:       Absolute path to the repository root.
        tests_dir:       Name of the tests directory (default 'tests').
                         Stubs are placed in <tests_dir>/stubs/.

    Returns:
        List of absolute paths to generated stub files (may be empty).
    """
    if not uncovered_funcs:
        console.print("[dim]  → No uncovered functions — skipping stub generation.[/dim]")
        return []

    # Filter to public functions only
    public = [f for f in uncovered_funcs if not _func_name(f).startswith("_")]
    if not public:
        console.print("[dim]  → All uncovered functions are private — skipping.[/dim]")
        return []

    # Group by module
    grouped: Dict[str, List[str]] = defaultdict(list)
    for qualified in public:
        module = _module_name(qualified)
        grouped[module].append(qualified)

    # Determine stub output directory
    root = Path(repo_root).resolve()
    stub_dir = root / tests_dir / _STUB_SUBDIR
    stub_dir.mkdir(parents=True, exist_ok=True)

    # Ensure stub_dir is a Python package (needed for pytest discovery)
    _ensure_init(stub_dir)

    generated: List[str] = []
    for module, qualifieds in grouped.items():
        path = _write_stub_file(module, qualifieds, stub_dir)
        if path:
            generated.append(path)

    console.print(
        f"[green]  ✓ Generated {len(generated)} stub file(s) in "
        f"{stub_dir.relative_to(root)}[/green]"
    )
    return generated


# ===========================================================================
# Stub File Writer
# ===========================================================================

def _write_stub_file(
    module: str,
    qualifieds: List[str],
    stub_dir: Path,
) -> str | None:
    """
    Write a stub test file for all uncovered functions in *module*.

    Args:
        module:     Dot-separated module name (e.g. 'src.utils').
        qualifieds: List of 'module.function' strings.
        stub_dir:   Directory to write into.

    Returns:
        Absolute file path if written, None on error.
    """
    stem = module.split(".")[-1]          # 'src.utils' → 'utils'
    filename = f"test_{stem}_stubs.py"
    file_path = stub_dir / filename

    # Idempotent — don't overwrite existing stubs
    if file_path.exists():
        console.print(
            f"[dim]  → {file_path.name} already exists — skipping.[/dim]"
        )
        return str(file_path)

    stubs = [_make_stub(q) for q in qualifieds]
    content = _build_file(module, stubs)

    try:
        file_path.write_text(content, encoding="utf-8")
        console.print(f"[blue]  + {file_path.name}[/blue] ({len(stubs)} stub(s))")
        return str(file_path)
    except OSError as exc:
        console.print(f"[yellow]  ⚠ Could not write {file_path.name}: {exc}[/yellow]")
        return None


# ===========================================================================
# Stub Builders
# ===========================================================================

def _make_stub(qualified: str) -> str:
    """
    Build a single pytest stub function string for 'module.function'.

    Example output:
        def test_parse_url():
            \"\"\"Stub for src.utils.parse_url — generated by ContribTriage.\"\"\"
            # TODO: implement this test
            raise NotImplementedError(
                "src.utils.parse_url has no test coverage — please add one."
            )
    """
    func = _func_name(qualified)
    return textwrap.dedent(f"""\
        def test_{func}():
            \"\"\"Stub for {qualified} — generated by ContribTriage.\"\"\"
            # TODO: implement this test
            raise NotImplementedError(
                "{qualified} has no test coverage — please add one."
            )
    """)


def _build_file(module: str, stubs: List[str]) -> str:
    """Assemble the full content of a stub test file."""
    header = textwrap.dedent(f"""\
        \"\"\"
        tests/stubs/test_{module.split('.')[-1]}_stubs.py

        AUTO-GENERATED by ContribTriage — Stage 4: Test Coverage Evaluation.
        These stub tests mark PUBLIC functions that have NO test coverage.

        HOW TO USE:
          1. Replace each `raise NotImplementedError(...)` with real assertions.
          2. Move the finished test to the main tests/ directory.
          3. Re-run ContribTriage to confirm coverage improved.

        Module: {module}
        Stubs:  {len(stubs)} function(s)
        \"\"\"

        import pytest

    """)
    separator = "\n\n"
    return header + separator.join(stubs)


# ===========================================================================
# Helpers
# ===========================================================================

def _module_name(qualified: str) -> str:
    """'src.utils.parse_url' → 'src.utils'"""
    parts = qualified.rsplit(".", 1)
    return parts[0] if len(parts) == 2 else "unknown"


def _func_name(qualified: str) -> str:
    """'src.utils.parse_url' → 'parse_url'"""
    return qualified.rsplit(".", 1)[-1]


def _ensure_init(directory: Path) -> None:
    """Create an __init__.py if it doesn't exist."""
    init = directory / "__init__.py"
    if not init.exists():
        init.write_text("# Generated by ContribTriage\n", encoding="utf-8")


# ===========================================================================
# Dep Import Alias Table
# ===========================================================================

# Maps lowercase pip package name → Python import name when they differ.
# This handles the most common mismatches; falls back to
# dep.replace('-', '_') for everything not listed here.
_IMPORT_ALIAS: Dict[str, str] = {
    "pillow":             "PIL",
    "scikit-learn":      "sklearn",
    "pyyaml":            "yaml",
    "beautifulsoup4":    "bs4",
    "python-dotenv":     "dotenv",
    "opencv-python":     "cv2",
    "typing-extensions": "typing_extensions",
    "python-dateutil":   "dateutil",
    "pyzmq":             "zmq",
    "attrs":             "attr",
    "pycparser":         "pycparser",
    "cryptography":      "cryptography",
    "pyarrow":           "pyarrow",
    "google-cloud-storage": "google.cloud.storage",
}


# ===========================================================================
# Public API — Dependency Importability Stubs
# ===========================================================================

def generate_dep_stubs(
    declared_deps: List[str],
    dep_ecosystem: Dict[str, str],
    repo_root: str,
    tests_dir: str = "tests",
) -> List[str]:
    """
    Generate pytest files that verify every declared dependency is importable.

    For Python deps: emits `import <dep>` wrapped in a `pytest.fail` guard.
    For Node deps:   emits a subprocess `node -e "require('<dep>')"` check.
    Other ecosystems (rust, go) are skipped — their build systems verify deps.

    The generated tests PASS when a dep is installed and FAIL with a
    clear error when it is missing.  The `ImportError` / subprocess stderr
    is surfaced as a `dep_error` by the test runner, triggering the Stage 5
    healing loop.

    Args:
        declared_deps:  List of package names from ProjectMeta.declared_deps.
        dep_ecosystem:  Map of {dep_name: ecosystem} from ProjectMeta.
        repo_root:      Absolute path to the repository root.
        tests_dir:      Tests directory name (default 'tests').

    Returns:
        List of absolute paths to generated stub files (may be empty).
    """
    if not declared_deps:
        console.print("[dim]  → No declared deps — skipping dep stub generation.[/dim]")
        return []

    # Separate by ecosystem
    python_deps = [
        d for d in declared_deps
        if dep_ecosystem.get(d, "").lower() == "python"
    ]
    node_deps = [
        d for d in declared_deps
        if dep_ecosystem.get(d, "").lower() in ("node", "nodejs")
    ]

    root    = Path(repo_root).resolve()
    stub_dir = root / tests_dir / _STUB_SUBDIR
    stub_dir.mkdir(parents=True, exist_ok=True)
    _ensure_init(stub_dir)

    generated: List[str] = []

    if python_deps:
        path = _write_dep_file(
            "python",
            python_deps,
            stub_dir,
            _make_python_dep_stub,
        )
        if path:
            generated.append(path)

    if node_deps:
        path = _write_dep_file(
            "node",
            node_deps,
            stub_dir,
            _make_node_dep_stub,
        )
        if path:
            generated.append(path)

    console.print(
        f"[green]  ✓ Dep stubs: {len(generated)} file(s) covering "
        f"{len(python_deps)} Python + {len(node_deps)} Node deps[/green]"
    )
    return generated


# ===========================================================================
# Dep Stub File Writer
# ===========================================================================

def _write_dep_file(
    ecosystem: str,
    deps: List[str],
    stub_dir: Path,
    stub_fn,
) -> str | None:
    """
    Write a dep-check stub file for one ecosystem.

    Args:
        ecosystem: 'python' or 'node'
        deps:      Package names for that ecosystem.
        stub_dir:  Directory to write into.
        stub_fn:   Function that builds one stub string per dep.

    Returns:
        Absolute file path if written, None on error.
    """
    filename  = f"test_deps_{ecosystem}_stubs.py"
    file_path = stub_dir / filename

    # Idempotent
    if file_path.exists():
        console.print(f"[dim]  → {file_path.name} already exists — skipping.[/dim]")
        return str(file_path)

    stubs   = [stub_fn(dep) for dep in deps]
    content = _build_dep_file(ecosystem, deps, stubs)

    try:
        file_path.write_text(content, encoding="utf-8")
        console.print(
            f"[blue]  + {file_path.name}[/blue] ({len(stubs)} dep test(s))"
        )
        return str(file_path)
    except OSError as exc:
        console.print(f"[yellow]  ⚠ Could not write {file_path.name}: {exc}[/yellow]")
        return None


# ===========================================================================
# Individual Stub Builders
# ===========================================================================

def _make_python_dep_stub(dep: str) -> str:
    """
    Build a pytest function that tries to `import <dep>` and fails clearly.

    Example output:
        def test_import_requests():
            \"\"\"Verify 'requests' is importable — generated by ContribTriage.\"\"\"
            try:
                import requests  # noqa: F401
            except ImportError as exc:
                pytest.fail(f"Dependency 'requests' is not installed. {exc}")
    """
    import_name = _dep_to_import_name(dep)
    safe_name   = dep.replace("-", "_").replace(".", "_")
    return textwrap.dedent(f"""\
        def test_import_{safe_name}():
            \"\"\"Verify '{dep}' is importable — generated by ContribTriage.\"\"\"
            try:
                import {import_name}  # noqa: F401
            except ImportError as exc:
                pytest.fail(f\"Dependency '{dep}' is not installed: {{exc}}\")
    """)


def _make_node_dep_stub(dep: str) -> str:
    """
    Build a pytest function that verifies a Node.js dep via subprocess.

    Example output:
        def test_import_axios():
            \"\"\"Verify 'axios' is available in the Node environment.\"\"\"
            import subprocess as _sp
            result = _sp.run(["node", "-e", "require('axios')"],
                             capture_output=True, text=True, timeout=10)
            if result.returncode != 0:
                pytest.fail(f"Node dep 'axios' unavailable: {result.stderr.strip()}")
    """
    safe_name = dep.replace("-", "_").replace("@", "").replace("/", "_")
    return textwrap.dedent(f"""\
        def test_import_{safe_name}():
            \"\"\"Verify Node dep '{dep}' is available — generated by ContribTriage.\"\"\"
            import subprocess as _sp
            result = _sp.run(
                ["node", "-e", "require('{dep}')"],
                capture_output=True, text=True, timeout=10,
            )
            if result.returncode != 0:
                pytest.fail(
                    f\"Node dependency '{dep}' is not installed: {{result.stderr.strip()}}\"
                )
    """)


def _build_dep_file(ecosystem: str, deps: List[str], stubs: List[str]) -> str:
    """Assemble the full content of a dep-check stub file."""
    header = textwrap.dedent(f"""\
        \"\"\"
        tests/stubs/test_deps_{ecosystem}_stubs.py

        AUTO-GENERATED by ContribTriage — Stage 4: Dependency Importability Check.

        Each test verifies that one declared dependency is actually installed
        in the current environment.

        HOW THESE WORK:
          PASS  → dependency is installed and importable—everything is fine.
          FAIL  → dependency is missing.  ContribTriage Stage 5 (self-healing)
                   will automatically attempt to install it.

        DO NOT DELETE these stubs while using ContribTriage.
        Once your environment is fully healed, they can be removed.

        Ecosystem : {ecosystem}
        Packages  : {len(deps)}
        \"\"\"

        import pytest

    """)
    separator = "\n\n"
    return header + separator.join(stubs)


# ===========================================================================
# Dep Name Helpers
# ===========================================================================

def _dep_to_import_name(dep: str) -> str:
    """
    Convert a pip package name to its Python import name.

    Uses _IMPORT_ALIAS for known mismatches (e.g. 'pillow' → 'PIL').
    Falls back to replacing hyphens/dots with underscores.

    Examples:
        'requests'       → 'requests'
        'scikit-learn'   → 'sklearn'
        'python-dotenv'  → 'dotenv'
        'my-cool-lib'    → 'my_cool_lib'
    """
    return _IMPORT_ALIAS.get(dep.lower(), dep.replace("-", "_").replace(".", "_"))
